name: Maestro Cloud E2E

on:
  workflow_dispatch: # This keeps your manual "Run workflow" button active

jobs:
  maestro-cloud:
    runs-on: ubuntu-latest
    timeout-minutes: 15 # Automatically cancels if it hangs too long
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Demo APK
        run: |
          echo "Downloading target APK..."
          curl -L "https://github.com/saucelabs/my-demo-app-android/releases/download/2.0.1/mda-2.0.1-22.apk" -o myapp.apk

      - name: Run Maestro Cloud Action
        id: maestro-upload
        uses: mobile-dev-inc/action-maestro-cloud@v2
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          project-id: ${{ secrets.MAESTRO_PROJECT_ID }}
          app-file: myapp.apk
          # Using '.' ensures your 'subflows' folder is included in the upload
          workspace: . 
          env: |
            USER_NAME=${{ secrets.USER_NAME }}
            USER_PWD=${{ secrets.USER_PWD }}

      - name: Display Report Link
        if: always()
        run: |
          echo "View Results: ${{ steps.maestro-upload.outputs.MAESTRO_CLOUD_CONSOLE_URL }}"
